# Recommendations + Content Calendar for Alfido Tech

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from pathlib import Path

data_path = Path('../data/exports')

master_df = pd.read_csv(data_path / 'master_df.csv')

In [3]:
master_df.head()

,id,image_link,user_id,created_dat,insta_filter_used,photo_type,name,created_time,private/public,post_count,verified_status,hashtag_count,hashtags,total_likes,total_comments,followers_received,following_count,total_engagement,engagement_per_follower
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,5,"concert, drunk, fun, party, smile",25,25,77,0,50,0.649351
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"beach, landscape, photography, sunrise",36,31,77,0,67,0.870130
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,1,beauty,38,27,77,0,65,0.844156
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fun, happy, lol, smile",38,32,77,0,70,0.909091
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo,Kenton_Kirlin,16-02-2017 18:22,yes,11,no,4,"fashion, hair, party, style",31,27,77,0,58,0.753247

In [ ]:
time_df = master_df.copy()
time_df['created_time'] = pd.to_datetime(time_df['created_time'], errors='coerce')
time_df['hour'] = time_df['created_time'].dt.hour
time_df['total_engagement'] = time_df['total_likes'] + time_df['total_comments']
time_df['day_of_week_num'] = time_df['created_time'].dt.dayofweek

print("Recommendations for Alfido Tech ")
# =======================================================
print(f"Time range : {time_df['created_time'].min()} to {time_df['created_time'].max()}")
print("Total Samples :\n")

#==================== DESCRIBING THE DATA ===========================
display(time_df[['created_time', 'hour', 'total_engagement']].describe())
print("\nSample:")


#====================== DISPLAYING THE DATA ============================
display(time_df[['created_time', 'hour', 'day_of_week_num', 'total_engagement']].head(5))

best_hour = time_df.groupby('hour')['total_engagement'].mean().idxmax()
print(f"Best hour for engagement: {best_hour}")

best_day = time_df.groupby('day_of_week_num')['total_engagement'].mean().idxmax()
print(f"Best day of the week for engagement: {best_day}")   

print(f"Total Engagement by Hour:\n{time_df.groupby('hour')['total_engagement'].sum()}")

Recommendations for Alfido Tech
Time range : 2016-05-06 13:04:00 to 2017-05-04 16:32:00
Total Samples :

                        created_time        hour  total_engagement
count                            257  257.000000        257.000000
mean   2016-10-31 17:04:29.883268608   13.233463         63.307393
min              2016-05-06 13:04:00    0.000000         50.000000
25%              2016-08-07 16:25:00    7.000000         60.000000
50%              2016-10-11 09:01:00   14.000000         63.000000
75%              2017-02-06 22:05:00   19.000000         66.000000
max              2017-05-04 16:32:00   23.000000         79.000000
std                              NaN    6.884650          4.810761

Sample:

         created_time  hour  day_of_week_num  total_engagement
0 2017-02-16 18:22:00    18                3                50
1 2017-02-16 18:22:00    18                3                67
2 2017-02-16 18:22:00    18                3                65
3 2017-02-16 18:22:00    18                3                70
4 2017-02-16 18:22:00    18                3                58

Best hour for engagement: 5
Best day of the week for engagement: 4
Total Engagement by Hour:
hour
0      386
1      823
2      641
3      554
5      333
6      522
7     1000
9      434
10     392
11     891
12    1258
13     555
14     814
15     132
16    1154
17     888
18    1386
19     766
20      63
21    1503
22     500
23    1275
Name: total_engagement, dtype: int64